# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 978932458b4f589d951e74610be68cf6349439b9dac117f60ee095897463a92153b5075d4c47395f652b02f11d8bd55d3ba3132bee5fc0bedb7c279b0b0dd121

test:
  secret_key_base: c258489d682ff39512659ffc55370ddedf1009aab0785166fc5712cc11593a435ef6364a5f9681241aadbf81018fb921efade38906fa35c5d154e01c7240a5fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
